### ISSUE TITLE
Missing library

### ISSUE THREAD

**Issue by msimoes79** [bigcat/ModbusDroid#1]
Hi BigCat,

Great app, i install it on my phone and it works very well. Now i'm trying use your source code but when i import it on eclipse i get the follow error:

"Project 'com.bencatlin.modbusdroid.OldVersion.ModbusDroid' is missing required library: 'D:/Users/bcatlin/Development/libraries/modbus4j/lib-ver-1.1/seroUtils.jar'    com.bencatlin.modbusdroid.OldVersion.ModbusDroid"

I downloaded the missing file from "SourceForge.net" and i get no error but when i run the compiled app on my phone, the app crashes. I think that is happen because my file "seroUtils.jar" isn't generated by your modified code. 

How can i compile this library? Can you help me?

Many thanks, best regards,
Marco

**Comment by gosr** [comment]
1. Right click the project in Eclipse.
2. Select Properties.
3. Go to Java Build Path.
4. Go to Libraries tab.
5. If seroUtils.jar appears with a red cross, mark and delete it. Then click Add External JARs and select your downloaded seroUtils.jar.
6. Go to Order and Export tab.
7. The seroUtils.jar must be checked.
8. Click OK, and clean your project.

**Comment by msimoes79** [comment]
Hi eightx2,

It work's!!! Many thanks.

Best regards,
Marco
