### ISSUE TITLE
Cannot run app 

### ISSUE THREAD

**Issue by pakatipk** [bigcat/ModbusDroid#2]
![sc1](https://f.cloud.github.com/assets/5994120/1585325/099b8278-521a-11e3-9b7c-8bd80dd5bff8.jpg)

After adding the seroUtils.jar file, there are 2 erroes and 35 warnings - as a picture
i tried to run this on phone without edit any parts of code but it cannot be

Anyway, i try to fix the errors and after i can run 
but just show the message 'Unfortunately ModbusDroid has stop'

**Comment by jameszhengruiqing** [comment]
Probably you could try to change to android v2.2.

**Comment by bigcat** [comment]
Yeah, unforunately I haven't had time (or inclination) to keep up with updating this for later versions of android.

Plus, I'm not super proud of this codebase, as I was really just wetting my teeth with android with this project anyway.  I started a re-write that will be probably android 4.0+ and be more well-architected, and easier to work with.  It is still early in its development, but feel free to check it out if you want, it is my other Modbus project on github (it requires android studio, and not eclipse though).
